sources:
  - name: raw
    description: Raw data from CSV files
    database: postgres
    schema: raw

    tables:
      - name: censusg01
      - name: censusg02
      - name: listing
      - name: nsw_lga_code
      - name: nsw_lga_suburb